version: '3'
services:
  db_notes:
    container_name: notes
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_notes
    image: postgres:alpine
    restart: always
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - 2181
    ports:
      - "2182:2181"


